favorites:
  - Bird Flight
  - Afternoon Classical
  - Hobo's Lullaby
  - The Early Music Show
  - The Moonshine Show
  - The Tennessee Border Show
  - Honky Tonkin'
  - Night Train
  - Bach Hour
wkcr:
  stream: 'http://kanga.college.columbia.edu:8000/listen.pls'
  schedule: http://www.studentaffairs.columbia.edu/wkcr/node/3/view
settings:
  cache_dir: ./tmp/cache
  mp3_dir: ./tmp/mp3
  feed_dir: /var/nginx/myhost.com/html/podcasts/wkcr # webserver dir
  base_url: "http://myhost.com/podcasts/wkcr" # webserver dir public url (keep it private!)
  streamripper: /usr/bin/streamripper
  mp3wrap: /usr/bin/mp3wrap
  pre_roll: 60 # seconds, start recordings early
  post_roll: 120 # seconds, keep recording a bit after
  cache_ttl: 86400 # seconds, used by schedule scraper
